/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFaceSwapRouteImport } from './routes/api/face-swap'
import { Route as ApiAudioRouteImport } from './routes/api/audio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaceSwapRoute = ApiFaceSwapRouteImport.update({
  id: '/api/face-swap',
  path: '/api/face-swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/face-swap': typeof ApiFaceSwapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/face-swap': typeof ApiFaceSwapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/face-swap': typeof ApiFaceSwapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/audio' | '/api/face-swap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/audio' | '/api/face-swap'
  id: '__root__' | '/' | '/api/audio' | '/api/face-swap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAudioRoute: typeof ApiAudioRoute
  ApiFaceSwapRoute: typeof ApiFaceSwapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/face-swap': {
      id: '/api/face-swap'
      path: '/api/face-swap'
      fullPath: '/api/face-swap'
      preLoaderRoute: typeof ApiFaceSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAudioRoute: ApiAudioRoute,
  ApiFaceSwapRoute: ApiFaceSwapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
