/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsVoiceRouteImport } from './routes/tools.voice'
import { Route as ToolsSpeechToTextRouteImport } from './routes/tools.speech-to-text'
import { Route as ToolsFaceSwapRouteImport } from './routes/tools.face-swap'
import { Route as ToolsCanvasEditorRouteImport } from './routes/tools.canvas-editor'
import { Route as ToolsAiVideoRouteImport } from './routes/tools.ai-video'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ApiVideoRouteImport } from './routes/api/video'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiFaceSwapRouteImport } from './routes/api/face-swap'
import { Route as ApiAudioRouteImport } from './routes/api/audio'
import { Route as ToolsResourcesKindRouteImport } from './routes/tools.resources.$kind'
import { Route as ApiReplicateRunRouteImport } from './routes/api/replicate.run'
import { Route as ApiAiTextRouteImport } from './routes/api/ai.text'
import { Route as ApiAiImageRouteImport } from './routes/api/ai.image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVoiceRoute = ToolsVoiceRouteImport.update({
  id: '/tools/voice',
  path: '/tools/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSpeechToTextRoute = ToolsSpeechToTextRouteImport.update({
  id: '/tools/speech-to-text',
  path: '/tools/speech-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFaceSwapRoute = ToolsFaceSwapRouteImport.update({
  id: '/tools/face-swap',
  path: '/tools/face-swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCanvasEditorRoute = ToolsCanvasEditorRouteImport.update({
  id: '/tools/canvas-editor',
  path: '/tools/canvas-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAiVideoRoute = ToolsAiVideoRouteImport.update({
  id: '/tools/ai-video',
  path: '/tools/ai-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaceSwapRoute = ApiFaceSwapRouteImport.update({
  id: '/api/face-swap',
  path: '/api/face-swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsResourcesKindRoute = ToolsResourcesKindRouteImport.update({
  id: '/tools/resources/$kind',
  path: '/tools/resources/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReplicateRunRoute = ApiReplicateRunRouteImport.update({
  id: '/api/replicate/run',
  path: '/api/replicate/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTextRoute = ApiAiTextRouteImport.update({
  id: '/api/ai/text',
  path: '/api/ai/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImageRoute = ApiAiImageRouteImport.update({
  id: '/api/ai/image',
  path: '/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/face-swap': typeof ApiFaceSwapRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/video': typeof ApiVideoRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/ai-video': typeof ToolsAiVideoRoute
  '/tools/canvas-editor': typeof ToolsCanvasEditorRoute
  '/tools/face-swap': typeof ToolsFaceSwapRoute
  '/tools/speech-to-text': typeof ToolsSpeechToTextRoute
  '/tools/voice': typeof ToolsVoiceRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/text': typeof ApiAiTextRoute
  '/api/replicate/run': typeof ApiReplicateRunRoute
  '/tools/resources/$kind': typeof ToolsResourcesKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/face-swap': typeof ApiFaceSwapRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/video': typeof ApiVideoRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/ai-video': typeof ToolsAiVideoRoute
  '/tools/canvas-editor': typeof ToolsCanvasEditorRoute
  '/tools/face-swap': typeof ToolsFaceSwapRoute
  '/tools/speech-to-text': typeof ToolsSpeechToTextRoute
  '/tools/voice': typeof ToolsVoiceRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/text': typeof ApiAiTextRoute
  '/api/replicate/run': typeof ApiReplicateRunRoute
  '/tools/resources/$kind': typeof ToolsResourcesKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/face-swap': typeof ApiFaceSwapRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/video': typeof ApiVideoRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/ai-video': typeof ToolsAiVideoRoute
  '/tools/canvas-editor': typeof ToolsCanvasEditorRoute
  '/tools/face-swap': typeof ToolsFaceSwapRoute
  '/tools/speech-to-text': typeof ToolsSpeechToTextRoute
  '/tools/voice': typeof ToolsVoiceRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/text': typeof ApiAiTextRoute
  '/api/replicate/run': typeof ApiReplicateRunRoute
  '/tools/resources/$kind': typeof ToolsResourcesKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api/audio'
    | '/api/face-swap'
    | '/api/transcribe'
    | '/api/video'
    | '/tools/$slug'
    | '/tools/ai-video'
    | '/tools/canvas-editor'
    | '/tools/face-swap'
    | '/tools/speech-to-text'
    | '/tools/voice'
    | '/api/ai/image'
    | '/api/ai/text'
    | '/api/replicate/run'
    | '/tools/resources/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api/audio'
    | '/api/face-swap'
    | '/api/transcribe'
    | '/api/video'
    | '/tools/$slug'
    | '/tools/ai-video'
    | '/tools/canvas-editor'
    | '/tools/face-swap'
    | '/tools/speech-to-text'
    | '/tools/voice'
    | '/api/ai/image'
    | '/api/ai/text'
    | '/api/replicate/run'
    | '/tools/resources/$kind'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api/audio'
    | '/api/face-swap'
    | '/api/transcribe'
    | '/api/video'
    | '/tools/$slug'
    | '/tools/ai-video'
    | '/tools/canvas-editor'
    | '/tools/face-swap'
    | '/tools/speech-to-text'
    | '/tools/voice'
    | '/api/ai/image'
    | '/api/ai/text'
    | '/api/replicate/run'
    | '/tools/resources/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAudioRoute: typeof ApiAudioRoute
  ApiFaceSwapRoute: typeof ApiFaceSwapRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiVideoRoute: typeof ApiVideoRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsAiVideoRoute: typeof ToolsAiVideoRoute
  ToolsCanvasEditorRoute: typeof ToolsCanvasEditorRoute
  ToolsFaceSwapRoute: typeof ToolsFaceSwapRoute
  ToolsSpeechToTextRoute: typeof ToolsSpeechToTextRoute
  ToolsVoiceRoute: typeof ToolsVoiceRoute
  ApiAiImageRoute: typeof ApiAiImageRoute
  ApiAiTextRoute: typeof ApiAiTextRoute
  ApiReplicateRunRoute: typeof ApiReplicateRunRoute
  ToolsResourcesKindRoute: typeof ToolsResourcesKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/voice': {
      id: '/tools/voice'
      path: '/tools/voice'
      fullPath: '/tools/voice'
      preLoaderRoute: typeof ToolsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/speech-to-text': {
      id: '/tools/speech-to-text'
      path: '/tools/speech-to-text'
      fullPath: '/tools/speech-to-text'
      preLoaderRoute: typeof ToolsSpeechToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/face-swap': {
      id: '/tools/face-swap'
      path: '/tools/face-swap'
      fullPath: '/tools/face-swap'
      preLoaderRoute: typeof ToolsFaceSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/canvas-editor': {
      id: '/tools/canvas-editor'
      path: '/tools/canvas-editor'
      fullPath: '/tools/canvas-editor'
      preLoaderRoute: typeof ToolsCanvasEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ai-video': {
      id: '/tools/ai-video'
      path: '/tools/ai-video'
      fullPath: '/tools/ai-video'
      preLoaderRoute: typeof ToolsAiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/face-swap': {
      id: '/api/face-swap'
      path: '/api/face-swap'
      fullPath: '/api/face-swap'
      preLoaderRoute: typeof ApiFaceSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/resources/$kind': {
      id: '/tools/resources/$kind'
      path: '/tools/resources/$kind'
      fullPath: '/tools/resources/$kind'
      preLoaderRoute: typeof ToolsResourcesKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/replicate/run': {
      id: '/api/replicate/run'
      path: '/api/replicate/run'
      fullPath: '/api/replicate/run'
      preLoaderRoute: typeof ApiReplicateRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/text': {
      id: '/api/ai/text'
      path: '/api/ai/text'
      fullPath: '/api/ai/text'
      preLoaderRoute: typeof ApiAiTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/image': {
      id: '/api/ai/image'
      path: '/api/ai/image'
      fullPath: '/api/ai/image'
      preLoaderRoute: typeof ApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAudioRoute: ApiAudioRoute,
  ApiFaceSwapRoute: ApiFaceSwapRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiVideoRoute: ApiVideoRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsAiVideoRoute: ToolsAiVideoRoute,
  ToolsCanvasEditorRoute: ToolsCanvasEditorRoute,
  ToolsFaceSwapRoute: ToolsFaceSwapRoute,
  ToolsSpeechToTextRoute: ToolsSpeechToTextRoute,
  ToolsVoiceRoute: ToolsVoiceRoute,
  ApiAiImageRoute: ApiAiImageRoute,
  ApiAiTextRoute: ApiAiTextRoute,
  ApiReplicateRunRoute: ApiReplicateRunRoute,
  ToolsResourcesKindRoute: ToolsResourcesKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
